### ISSUE TITLE
Нюансы которые хотелось бы поправить

### ISSUE THREAD

**Issue by dmifedorenko** [JustJoni/test_for_100sp#1]
1. В корне проекта 2 бинарных файла от composer - composer + composer.phar. Их лучше убрать из под контроля git. Бинарные файлы, утилиты, программы лучше не коммитить в git.

2. Папка vendor - это внешние зависимости, их тоже не надо хранить в git. Уберите их из под контроля версий. Я в любой момент смогу выполнить `composer install` из корня проекта и получу локально папку vendor.

3. Папку vendor и любые другие внешние зависимости лучше добавить в .gitignore файл.

4. В дампах БД таблиц purchase_type_test и purchase_test хочется
	- поменять тип поля id с int на int unsigned
	- charset таблицам сразу добавить явно, лучше utf8mb4 указать
	- Можно узнать почему у 2х таблиц, для полей name используется разный тип? char и varchar - в чем причина такого выбора типов?

5. Форматирование кода "плавает"
	- хочется в composer в require-dev секцию добавить пакет friendsofphp/php-cs-fixer
	- в composer.json же в секцию scripts (https://getcomposer.org/doc/articles/scripts.md) вызов `vendor/bin/php-cs-fixer fix --diff -vvv --allow-risky=yes`
	- Весь код приложения (кроме vendor конечно) хочется привести к PSR стандарту и прогнать для него php-cs-fixer fix. Если php-cs-fixer будет показывать ошибки, то их надо исправить в коде.

**Comment by JustJoni** [comment]
1-3. Хорошо, уберу.
4. поменяю, опечатка, должно было быть varchar.
5. Вечером ознакомлюсь, и прогоню, поправлю.

**Comment by JustJoni** [comment]
> 1. В корне проекта 2 бинарных файла от composer - composer + composer.phar. Их лучше убрать из под контроля git. Бинарные файлы, утилиты, программы лучше не коммитить в git.
> 2. Папка vendor - это внешние зависимости, их тоже не надо хранить в git. Уберите их из под контроля версий. Я в любой момент смогу выполнить `composer install` из корня проекта и получу локально папку vendor.
> 3. Папку vendor и любые другие внешние зависимости лучше добавить в .gitignore файл.
> 4. В дампах БД таблиц purchase_type_test и purchase_test хочется
>    
>    * поменять тип поля id с int на int unsigned
>    * charset таблицам сразу добавить явно, лучше utf8mb4 указать
>    * Можно узнать почему у 2х таблиц, для полей name используется разный тип? char и varchar - в чем причина такого выбора типов?
> 5. Форматирование кода "плавает"
>    
>    * хочется в composer в require-dev секцию добавить пакет friendsofphp/php-cs-fixer
>    * в composer.json же в секцию scripts (https://getcomposer.org/doc/articles/scripts.md) вызов `vendor/bin/php-cs-fixer fix --diff -vvv --allow-risky=yes`
>    * Весь код приложения (кроме vendor конечно) хочется привести к PSR стандарту и прогнать для него php-cs-fixer fix. Если php-cs-fixer будет показывать ошибки, то их надо исправить в коде.

1-3. Хорошо, уберу.
4. поменяю, опечатка, должно было быть varchar.
5. Вечером ознакомлюсь, и прогоню, поправлю.
