### ISSUE TITLE
Добавление разных городов в выгружаемые данные

### ISSUE THREAD

**Issue by dmifedorenko** [JustJoni/test_for_100sp#2]
Текущий код работает только с одним городом - Владивосток. Сейчас мы не можем одновременно выгрузить данные для 2-3-4х разных городов.

Надо сделать правки кода так, чтобы он мог поддерживать загрузку одновременно нескольких городов. Хочется иметь на входе список вида:
- https://www.100sp.ru/vladivostok
- https://www.100sp.ru/khabarovsk
- https://www.100sp.ru/komsomolsk-na-amure

Дополнительно в коде надо сделать классы или методы для вынимая данных из БД по определенному городу. Чтобы я смог в будущем использовать их для вывода списка покупок на экран или в консоль, например. Т.е. мы делаем не только запись в БД но и готовим чтение из БД уже записанных ранее данных.

**Comment by JustJoni** [comment]
Это весь список городов или нужно вытягивать список городов и проходиться по всем полученным городам?

**Comment by dmifedorenko** [comment]
Нет, весь список городов не нужен. На входе у скрипта должен быть фиксированный список из нескольких городов который заранее заполняется вручную, а не стягивается скриптом с сайта.

Можно сделать только 3 указанных выше города, этого будет достаточно.

**Comment by JustJoni** [comment]
Добавил всё необходимое
